"use client";

import { keepPreviousData, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { bulkDeleteDailyReports, createDailyReport, deleteDailyReport, duplicateDailyReport, getDailyReport, getDailyReportExport, getDailyReportImport, getDailyReportLookups, getDailyReportProducts, getDailyReports, importDailyReports, queueDailyReportExport, updateDailyReport, workflowDailyReport, type DailyReportPayload, type DailyReportQuery } from "./services";

export const dailyReportKeys = { all: ["daily-reports"] as const, list: (query: DailyReportQuery) => ["daily-reports", "list", query] as const, lookups: ["daily-reports", "lookups"] as const };
export function useDailyReports(query: DailyReportQuery) { return useQuery({ queryKey: dailyReportKeys.list(query), queryFn: () => getDailyReports(query), placeholderData: keepPreviousData, staleTime: 30_000 }); }
export function useDailyReportLookups() { return useQuery({ queryKey: dailyReportKeys.lookups, queryFn: getDailyReportLookups, staleTime: 300_000 }); }
export function useDailyReportProducts(search: string) { return useQuery({ queryKey: ["daily-reports", "products", search], queryFn: () => getDailyReportProducts(search), staleTime: 300_000 }); }
export function useCreateDailyReport() { const client = useQueryClient(); return useMutation({ mutationFn: (payload: DailyReportPayload) => createDailyReport(payload), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useUpdateDailyReport() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: number; payload: DailyReportPayload }) => updateDailyReport(id, payload), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useDeleteDailyReport() { const client = useQueryClient(); return useMutation({ mutationFn: (id: number) => deleteDailyReport(id), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useBulkDeleteDailyReports() { const client = useQueryClient(); return useMutation({ mutationFn: (ids: number[]) => bulkDeleteDailyReports(ids), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useDailyReport(id: number) { return useQuery({ queryKey: ["daily-reports", "detail", id], queryFn: () => getDailyReport(id), enabled: Boolean(id) }); }
export function useDailyReportWorkflow() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, action }: { id: number; action: "submit" | "review" | "approve" | "reject" | "lock" }) => workflowDailyReport(id, action), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useBulkDailyReportWorkflow() { const client = useQueryClient(); return useMutation({ mutationFn: ({ ids, action }: { ids: number[]; action: "submit" | "review" | "lock" }) => Promise.all(ids.map((id) => workflowDailyReport(id, action))), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useDuplicateDailyReport() { const client = useQueryClient(); return useMutation({ mutationFn: (id: number) => duplicateDailyReport(id), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useQueueDailyReportExport() { return useMutation({ mutationFn: (filters: Record<string, number | string | undefined>) => queueDailyReportExport(filters) }); }
export function useDailyReportExport(id?: number) { return useQuery({ queryKey: ["daily-report-exports", id], queryFn: () => getDailyReportExport(id as number), enabled: Boolean(id), refetchInterval: (query) => query.state.data?.status === "completed" || query.state.data?.status === "failed" ? false : 1500 }); }
export function useImportDailyReports() { const client = useQueryClient(); return useMutation({ mutationFn: ({ file, plantId }: { file: File; plantId: number }) => importDailyReports(file, plantId), onSuccess: () => client.invalidateQueries({ queryKey: dailyReportKeys.all }) }); }
export function useDailyReportImport(id?: number) { return useQuery({ queryKey: ["daily-report-imports", id], queryFn: () => getDailyReportImport(id as number), enabled: Boolean(id), refetchInterval: (query) => query.state.data?.status === "completed" || query.state.data?.status === "completed_with_errors" || query.state.data?.status === "failed" ? false : 1500 }); }
