import { apiClient } from "@/services/api-client";
import type { ApiResponse, Paginated } from "@/types/api";
import type { DailyReport, DailyReportLookups, DailyReportResult, DailyReportStatus } from "./types";

export type DailyReportQuery = { page?: number; per_page?: number; search?: string; period?: "daily" | "weekly" | "monthly" | "yearly"; plant_id?: number; machine_id?: number; shift_id?: number; product_id?: number; product_type?: "FG" | "WIP"; defect_id?: number; checker_id?: number; qa_checker_id?: number; qa_checker_2_id?: number; result?: string; status?: DailyReportStatus; production_date?: string; production_date_from?: string; production_date_to?: string; sort?: string; direction?: "asc" | "desc" };
export type DailyReportPayload = { plant_id: number; machine_id: number; shift_id: number; product_id: number; product_type: "WIP" | "FG"; checker_id: number; checker_2_id?: number; po_number: string; output_box: number; production_date: string; defects: { defect_id: number; quantity: number; remarks?: string }[]; remarks?: string; result?: DailyReportResult; finding_range_box?: string; finding_observation?: string };
export type DailyReportExport = { id: number; status: "queued" | "processing" | "completed" | "failed"; file_path?: string; error_message?: string; created_at: string };
export type DailyReportImportStatus = { id: number; file_name: string; status: "queued" | "processing" | "completed" | "completed_with_errors" | "failed"; processed_rows: number; imported_reports: number; failed_rows: number; errors?: { row: number; message: string }[]; error_message?: string | null };
type DailyReportCollectionResponse = ApiResponse<Paginated<DailyReport> | DailyReport[]> & { meta?: { current_page?: number; last_page?: number; per_page?: number; total?: number } };
export async function importDailyReports(file: File, plantId: number) { const form = new FormData(); form.append("file", file); form.append("plant_id", String(plantId)); const { data } = await apiClient.post<ApiResponse<DailyReportImportStatus>>("/daily-reports/import", form, { headers: { "Content-Type": "multipart/form-data" } }); return data.data; }
export async function getDailyReportImport(id: number) { const { data } = await apiClient.get<ApiResponse<DailyReportImportStatus>>(`/daily-reports/imports/${id}`); return data.data; }
export async function getDailyReports(params: DailyReportQuery = {}) { const query = { per_page: 20, ...params }; const { data } = await apiClient.get<DailyReportCollectionResponse>("/daily-reports", { params: query }); if (!Array.isArray(data.data)) return data.data; return { data: data.data, current_page: data.meta?.current_page ?? Number(query.page ?? 1), last_page: data.meta?.last_page ?? (data.data.length ? Number(query.page ?? 1) : 1), per_page: data.meta?.per_page ?? Number(query.per_page ?? 20), total: data.meta?.total ?? data.data.length }; }
export async function getDailyReportLookups() { const { data } = await apiClient.get<ApiResponse<DailyReportLookups>>("/daily-reports/lookups"); return data.data; }
export async function getDailyReportProducts(search = "") { const { data } = await apiClient.get<ApiResponse<DailyReportLookups["products"]>>("/daily-reports/lookups/products", { params: { search } }); return data.data; }
export async function createDailyReport(payload: DailyReportPayload) { const { data } = await apiClient.post<ApiResponse<DailyReport>>("/daily-reports", payload); return data.data; }
export async function updateDailyReport(id: number, payload: DailyReportPayload) { const { data } = await apiClient.put<ApiResponse<DailyReport>>(`/daily-reports/${id}`, payload); return data.data; }
export async function deleteDailyReport(id: number) { await apiClient.delete(`/daily-reports/${id}`); }
export async function getDailyReport(id: number) { const { data } = await apiClient.get<ApiResponse<DailyReport>>(`/daily-reports/${id}`); return data.data; }
export async function workflowDailyReport(id: number, action: "submit" | "review" | "approve" | "reject" | "lock") { const { data } = await apiClient.post<ApiResponse<DailyReport>>(`/daily-reports/${id}/${action}`); return data.data; }
export async function duplicateDailyReport(id: number) { const { data } = await apiClient.post<ApiResponse<DailyReport>>(`/daily-reports/${id}/duplicate`); return data.data; }
export async function printDailyReport(id: number) { const { data } = await apiClient.get<Blob>(`/daily-reports/${id}/print`, { responseType: "blob" }); return data; }
export async function queueDailyReportExport(filters: Record<string, number | string | undefined>) { const { data } = await apiClient.post<ApiResponse<DailyReportExport>>("/daily-reports/export", filters); return data.data; }
export async function getDailyReportExport(id: number) { const { data } = await apiClient.get<ApiResponse<DailyReportExport>>(`/daily-reports/exports/${id}`); return data.data; }
export function dailyReportExportDownloadUrl(id: number) { return `${apiClient.defaults.baseURL}/daily-reports/exports/${id}/download`; }
