<?php

namespace Database\Seeders;

use App\Models\Defect;
use Illuminate\Database\Seeder;

class DefectMasterSeeder extends Seeder
{
    public function run(): void
    {
        $defects = [
            ['BARCODE GESER', 'MAJOR'], ['BLACK SPOT > STANDARD', 'MINOR'], ['BLOK BELANG', 'MAJOR'], ['BORE BUNTU', 'CRITICAL'], ['BORE FLASH', 'MAJOR'],
            ['BORE OVAL', 'CRITICAL'], ['BORE TIDAK SESUAI STANDARD', 'CRITICAL'], ['BORE UNMOULDED', 'CRITICAL'], ['CAP DALAM TUBE', 'CRITICAL'], ['CAP FLASH', 'MINOR'],
            ['CAP KEBUKA', 'CRITICAL'], ['CAP KENDOR', 'CRITICAL'], ['CAP KOTOR', 'MAJOR'], ['CAP MIRING', 'MAJOR'], ['CAP NOT POSITIONING', 'MAJOR'],
            ['CAP PECAH', 'CRITICAL'], ['CAP RENGGANG', 'MINOR'], ['CAP SCRATCH', 'MAJOR'], ['CAP TERBALIK', 'CRITICAL'], ['CAP UNMOULDED', 'UNACCEPTABLE'],
            ['COLLAPS', 'MAJOR'], ['ENDSEAL GELOMBANG', 'MINOR'], ['ENDSEAL MELELEH', 'MINOR'], ['ENDSEAL MIRING', 'MINOR'], ['ENDSEAL SERABUT', 'MINOR'],
            ['ENDSEAL TIDAK MENEMPEL', 'CRITICAL'], ['EYEMARK NAIK-TURUN', 'MAJOR'], ['GRADASI BELANG', 'MAJOR'], ['GRADASI KASAR', 'MAJOR'], ['GRADASI PUTUS', 'MAJOR'],
            ['HEADER GESER', 'CRITICAL'], ['HEADER DEFORM', 'MAJOR'], ['HEADER FLASH', 'MAJOR'], ['HEADER KONTAMINASI', 'MAJOR'], ['HEADER MELIPAT', 'CRITICAL'],
            ['HEADER MIRING', 'CRITICAL'], ['HEADER SOBEK', 'CRITICAL'], ['HEADER TERBALIK', 'CRITICAL'], ['HEADER TIDAK LENGKET', 'CRITICAL'], ['HEADER TIDAK PENUH', 'CRITICAL'],
            ['HEADER TURUN', 'MAJOR'], ['HEADER UNMOULDED', 'CRITICAL'], ['HINGE CAP PUTUS', 'CRITICAL'], ['KETIDAKSESUAIAN KONDISI PACKING', 'UNACCEPTABLE'], ['KONDISI BOX TIDAK SESUAI STANDARD', 'CRITICAL'],
            ['KONTAMINASI WARNA', 'MAJOR'], ['KOTOR BAGIAN DALAM (DEBU)', 'MAJOR'], ['KOTOR BAGIAN DALAM (EMBALASE)', 'MAJOR'], ['KOTOR BAGIAN DALAM (OLI)', 'MAJOR'], ['KOTOR BAGIAN DALAM (TINTA)', 'MAJOR'],
            ['KOTOR BAGIAN LUAR (DEBU)', 'MAJOR'], ['KOTOR BAGIAN LUAR (OLI)', 'MAJOR'], ['KOTOR BAGIAN LUAR (TINTA)', 'MAJOR'], ['KOTOR PRINT', 'MAJOR'], ['LABEL BOX TIDAK SESUAI', 'UNACCEPTABLE'],
            ['LABEL/STICKER BINTIK HITAM KARENA MATERIAL', 'MINOR'], ['LABEL/STICKER BUBBLE KARENA KOTOR', 'MINOR'], ['LABEL/STICKER BUBBLE KARENA UDARA', 'MINOR'], ['LABEL/STICKER DELAMINASI', 'CRITICAL'], ['LABEL/STICKER KURANG LENGKET', 'CRITICAL'],
            ['LABEL/STICKER MELIPAT', 'MAJOR'], ['LABEL/STICKER NAIK', 'MAJOR'], ['LAIN-LAIN', '-'], ['LAYOUT GESER/MISREGISTER', 'MAJOR'], ['LAYOUT LABEL/STICKER TIDAK SESUAI STANDARD', 'MAJOR'],
            ['LAYOUT NAIK', 'MAJOR'], ['LAYOUT TURUN', 'MAJOR'], ['LIPRING CACAT', 'CRITICAL'], ['LOF < STANDARD', 'CRITICAL'], ['LOF > STANDARD', 'CRITICAL'],
            ['MISREGISTERED (SELIP/MBAYANG)', 'MAJOR'], ['MISSING PRINT (PETHAL)', 'MAJOR'], ['NO CAP', 'CRITICAL'], ['NO VARNISH', 'CRITICAL'], ['OVERLAP RENGGANG', 'MINOR'],
            ['PLASTIK LAYER TIDAK ADA', 'UNACCEPTABLE'], ['POTONGAN ENDSEAL TIDAK RATA', 'MINOR'], ['POTONGAN SLEEVE TIDAK RATA (SERABUT)', 'MINOR'], ['PRINT BLOBOR', 'MAJOR'], ['PRINT TEBAL (BOLD)', 'MAJOR'],
            ['PRINT TIPIS', 'MAJOR'], ['SCRATCH', 'MAJOR'], ['SERABUT (PROSES CAPPING)', 'MINOR'], ['SLEEVE GARIS', 'MAJOR'], ['SLEEVE KONTAMINASI', 'MAJOR'],
            ['SLEEVE MEKAR', 'MAJOR'], ['SLEEVE NERAWANG', 'MAJOR'], ['SLEEVE PEKAT', 'MAJOR'], ['SLEEVE PORI-PORI KASAR', 'MINOR'], ['SLEEVE TEBAL TIPIS', 'MAJOR'],
            ['STAMPING BURAM', 'MINOR'], ['STAMPING CAP RONTOK', 'MAJOR'], ['STAMPING PETHAL', 'MAJOR'], ['STAMPING SELIP', 'MINOR'], ['STAMPING TIDAK RATA', 'MINOR'],
            ['STAMPING TUMPUL', 'MINOR'], ['TERDAPAT RAMBUT DI DALAM TUBE', 'UNACCEPTABLE'], ['TERDAPAT SERANGGA DI DALAM TUBE', 'UNACCEPTABLE'], ['TINGGI TUBE TIDAK SESUAI STANDARD', 'MAJOR'], ['TONE WARNA PRINTING TIDAK SESUAI STANDARD', 'UNACCEPTABLE'],
            ['TONE WARNA SLEEVE TIDAK SESUAI STANDARD', 'UNACCEPTABLE'], ['TOP SEAL KROAK', 'CRITICAL'], ['TOP SEAL MIRING', 'MAJOR'], ['TORSI < STANDARD', 'CRITICAL'], ['TUBE KERITING', 'MAJOR'],
            ['TUBE MELENGKUNG', 'MAJOR'], ['TUBE PENYOK', 'CRITICAL'], ['ULIR CACAT', 'CRITICAL'], ['UNMELTING', 'MAJOR'], ['VARNISH BERLUBANG/BERCAK', 'MINOR'],
            ['VARNISH KASAR', 'MINOR'], ['VARNISH MAMEL', 'MAJOR'], ['VARNISH MENGGUMPAL', 'MINOR'], ['VARNISH MERINTIS', 'MINOR'], ['VARNISH NAIK-TURUN', 'MINOR'],
            ['VARNISH TIDAK RATA', 'MINOR'], ['VARNISH TIPIS', 'MINOR'], ['WARNA < LOWER CRB', 'MAJOR'], ['WARNA > UPPER CRB', 'MAJOR'], ['WARNA HEADER TIDAK SESUAI STANDARD', 'MAJOR'],
            ['WARNA LABEL/STICKER TIDAK SESUAI STANDARD', 'MAJOR'], ['WARNA SLEEVE TIDAK SESUAI STANDARD', 'MAJOR'], ['WARNA TIDAK SOLID', 'MAJOR'], ['WHITE GAP > STANDARD', 'MINOR'], ['WHITE SPOT > STANDARD', 'MINOR'],
        ];

        foreach ($defects as $index => [$name, $category]) {
            Defect::updateOrCreate(
                ['code' => sprintf('DEF-%03d', $index + 1)],
                ['name' => $name, 'description' => $name, 'category' => $category, 'is_active' => true],
            );
        }
    }
}
