export type MasterModule = "plants" | "lines" | "machines" | "shifts" | "products" | "defects" | "qa-checkers";
export type MasterRecord = { id: number;[key: string]: unknown };
export type MasterQuery = { page?: number; per_page?: number; search?: string; plant_id?: number; line_id?: number; category?: string; is_active?: boolean; sort?: string; direction?: "asc" | "desc" };
export type MasterPayload = Record<string, string | number | boolean | null | undefined>;
export type MasterColumn = { key: string; label: string; sortable?: boolean };
export type MasterConfig = { module: MasterModule; title: string; singular: string; description: string; columns: MasterColumn[]; filter?: "category" | "plant"; fields: string[] };

export const masterConfigs: Record<MasterModule, MasterConfig> = {
  plants: { module: "plants", title: "Plants", singular: "plant", description: "Manage production sites used across the QMS.", columns: [{ key: "code", label: "Code", sortable: true }, { key: "name", label: "Name", sortable: true }, { key: "description", label: "Description" }, { key: "is_active", label: "Status", sortable: true }], fields: ["code", "name", "description", "is_active"] },
  lines: { module: "lines", title: "Lines", singular: "line", description: "Manage production lines and their plant ownership.", columns: [{ key: "code", label: "Code", sortable: true }, { key: "name", label: "Name", sortable: true }, { key: "plant", label: "Plant" }, { key: "description", label: "Description" }, { key: "is_active", label: "Status" }], filter: "plant", fields: ["plant_id", "code", "name", "description", "is_active"] },
  machines: { module: "machines", title: "Machines", singular: "machine", description: "Manage machines assigned to plants.", columns: [{ key: "machine_number", label: "Machine No.", sortable: true }, { key: "code", label: "Code", sortable: true }, { key: "name", label: "Name" }, { key: "plant", label: "Plant" }, { key: "is_active", label: "Status" }], filter: "plant", fields: ["plant_id", "code", "name", "machine_number", "description", "is_active"] },
  shifts: { module: "shifts", title: "Shifts", singular: "shift", description: "Configure operating shift schedules.", columns: [{ key: "code", label: "Code", sortable: true }, { key: "name", label: "Name", sortable: true }, { key: "start_time", label: "Start" }, { key: "end_time", label: "End" }, { key: "is_active", label: "Status" }], fields: ["code", "name", "start_time", "end_time", "is_active"] },
  products: { module: "products", title: "Products", singular: "product", description: "Maintain products assigned to each plant.", columns: [{ key: "mm_number", label: "MM Number", sortable: true }, { key: "name", label: "Item Name" }, { key: "plant", label: "Plant" }, { key: "qty_per_box", label: "Qty / Box", sortable: true }, { key: "description", label: "Description" }, { key: "is_active", label: "Status" }], filter: "plant", fields: ["plant_id", "mm_number", "name", "description", "qty_per_box", "is_active"] },
  defects: { module: "defects", title: "Defects", singular: "defect", description: "Classify and maintain quality defect definitions.", columns: [{ key: "code", label: "Code", sortable: true }, { key: "name", label: "Name", sortable: true }, { key: "category", label: "Category", sortable: true }, { key: "description", label: "Description" }, { key: "is_active", label: "Status" }], filter: "category", fields: ["code", "name", "category", "description", "is_active"] },
  "qa-checkers": { module: "qa-checkers", title: "QA Checkers", singular: "QA checker", description: "Manage QA checkers assigned to production plants.", columns: [{ key: "employee_number", label: "Employee No.", sortable: true }, { key: "name", label: "Name", sortable: true }, { key: "position", label: "Position" }, { key: "plant", label: "Plant" }, { key: "is_active", label: "Status", sortable: true }], filter: "plant", fields: ["employee_number", "name", "position", "plant_id", "is_active"] },
};
